title: Learning Journal
author: Raunak Ranjan
email: raunaq.ranjan@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  The blog records my learnings, my little curious adventure into multiple domains...

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  raunaq-ranjan # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
